INVITE sip:sip.provider.com SIP/2.0
Via:SIP/2.0/UDP 172.16.254.66:5060;branch=z9hG4bK3e5380d454981e88702eb2269669462;rport
From:"Bob" <sip:bob@sip.provider.com>;tag=3718850509
To:"Alice" <sip:alice@sip.provider.com>
Call-ID:306366781@172_16_254_66
CSeq:3 INVITE
Max-Forwards:70
Allow:INVITE,ACK,CANCEL,BYE,OPTIONS,INFO,SUBSCRIBE,NOTIFY,REFER,UPDATE
Contact: <sip:bob@172.16.254.66:5060>
Expires:1800
User-Agent:C530 IP/42.245.00.000.000
Content-Length:11


Hello World
